
services:
  prolog-api:
    build:
      context: ./backend/
    ports:
      - "8090:8090"
    networks:
      - prolog-network
    volumes:
      - ./backend/src:/app/src

  frontend:
    build:
      context: ./frontend/
    ports:
      - "8080:8080"
    networks:
      - prolog-network
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-production}  # Default to production, can be overridden
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Map external port 80 to internal port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx configuration
    networks:
      - prolog-network
    depends_on:
      - prolog-api
      - frontend

networks:
  prolog-network:
    driver: bridge
      

volumes:
  node_modules: