
services:
  prolog-api:
    build:
      context: ./backend/
    ports:
      - "8090:8090"

  frontend:
    build:
      context: ./frontend/
    ports:
      - "8080:8080"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Map external port 80 to internal port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx configuration
    depends_on:
      - prolog-api
      - frontend
      